//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace autocomplete.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMPLOYEE
    {
        public int EMPLOYEE_ID { get; set; }
        public int PERSON_ID { get; set; }
        public Nullable<int> DISTRIBUTION_HOUSE_ID { get; set; }
        public Nullable<int> SUPERVISOR_ID { get; set; }
        public string EMPLOYEE_CODE { get; set; }
        public Nullable<int> EMPLOYEE_TYPE_ID { get; set; }
        public Nullable<System.DateTime> JOINING_DATE { get; set; }
        public Nullable<long> MINIMUM_INVESTMENT { get; set; }
        public string OTHER_FINANCIAL { get; set; }
        public Nullable<int> VEHICLE_TYPE_ID { get; set; }
        public Nullable<int> PROVIDER_ID { get; set; }
        public string NEAREST_DISTRIBUTION_MARKET { get; set; }
        public Nullable<int> DISTANCE_FROM_DISTRIBUTION { get; set; }
        public string SERVICE_DESCRIPTION { get; set; }
        public string PREVIOUS_PD_DETAIL { get; set; }
        public Nullable<int> EMPLOYEE_ROLE_STATUS_ID { get; set; }
        public Nullable<int> DISTRIBUTION_SPLIT_ID { get; set; }
        public Nullable<System.DateTime> START_DATE { get; set; }
        public Nullable<System.DateTime> END_DATE { get; set; }
        public Nullable<bool> ACTIVE { get; set; }
        public string REMARKS { get; set; }
        public Nullable<int> CREATED_BY { get; set; }
        public Nullable<System.DateTime> CRAETED_DATE { get; set; }
        public Nullable<int> UPDATED_BY { get; set; }
        public Nullable<System.DateTime> UPDATED_DATE { get; set; }
    
        public virtual PERSON PERSON { get; set; }
    }
}
