//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace autocomplete.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class PERSON
    {
        public PERSON()
        {
            this.EMPLOYEES = new HashSet<EMPLOYEE>();
        }
    
        public int PERSON_ID { get; set; }
        public string PERSON_NAME { get; set; }
        public string MOBILE { get; set; }
        public string MOTHERS_NAME { get; set; }
        public string FATHERS_NAME { get; set; }
        public string SECOND_CONTACT { get; set; }
        public string EDUCATIONAL_QUALIFICATION { get; set; }
        public Nullable<System.DateTime> DATE_OF_BIRTH { get; set; }
        public Nullable<int> IDENTITY_CARD_TYPE { get; set; }
        public string NID { get; set; }
        public Nullable<int> MARITAL_STATUS_ID { get; set; }
        public Nullable<int> FAMILY_MEMBER_NO { get; set; }
        public Nullable<int> MALE_NO { get; set; }
        public Nullable<int> FEMALE_NO { get; set; }
        public string NATIONALITY { get; set; }
        public Nullable<int> RELIGION_ID { get; set; }
        public string RELIGION_SPECIFY { get; set; }
        public Nullable<int> GENDER_ID { get; set; }
        public string PERMANENT_ADDRESS { get; set; }
        public string MAILING_ADDRESS { get; set; }
        public Nullable<int> DISTRICT_ID { get; set; }
        public Nullable<int> THANA_ID { get; set; }
        public Nullable<int> POST_OFFICE_ID { get; set; }
        public Nullable<int> UNION_NAME_ID { get; set; }
        public string VILLAGE_NAME { get; set; }
        public string CARE_OF { get; set; }
        public Nullable<int> PERMANENT_DISTRICT_ID { get; set; }
        public Nullable<int> PERMANENT_THANA_ID { get; set; }
        public Nullable<int> PERMANENT_POST_OFFICE_ID { get; set; }
        public Nullable<int> PERMANENT_UNION_NAME_ID { get; set; }
        public string PERMANENT_VILLAGE_NAME { get; set; }
        public string PERMANENT_CARE_OF { get; set; }
        public string PHONE { get; set; }
        public string EMAIL { get; set; }
        public Nullable<bool> ACTIVE { get; set; }
        public string REMARKS { get; set; }
        public Nullable<int> ENTERED_BY { get; set; }
        public Nullable<System.DateTime> ENTERED_DATE { get; set; }
        public Nullable<int> UPDATE_BY { get; set; }
        public Nullable<System.DateTime> UPDATE_DATE { get; set; }
        public Nullable<int> NATIONALITY_ID { get; set; }
        public string PERSON_IMAGE { get; set; }
    
        public virtual ICollection<EMPLOYEE> EMPLOYEES { get; set; }
    }
}
